### ISSUE TITLE
Bots seem think they collide with other players when I turn off players colliding with other players?

### ISSUE THREAD

**Issue by Gvbavx** [T-Rizzle12/Custom-Gmod-Bot#48] opened 2024-03-05 12:44 UTC
https://github.com/T-Rizzle12/Custom-Gmod-Bot/assets/145967852/a1a52d71-f357-427e-80cf-33e986fb9af5

https://github.com/T-Rizzle12/Custom-Gmod-Bot/assets/145967852/fb447834-d43e-4817-9865-33ee2cb1cb3a

Bots seem still try to avoiding collide with other players when I have anti-collisions enabled?
This can happen in some maps that have anti-collisions enabled.
Addons I used:No Player Collision, Custom Gmod Bot

**Comment by T-Rizzle12** [comment] 2024-03-05 17:05
This is an issue with the internal AI and how it checks for objects it can collide with. I will look into a possible fix for this.

**Comment by T-Rizzle12** [comment] 2024-06-03 03:35
I should be able to fix the following situations for player collision code.
- If SetNoCollideWithTeammates is set to true and the bot's team is between 1-4
- ~~If SetCustomCollisionCheck is set to true and I call the ShouldCollide Hook~~ (Actually it appears that bots automatically work with this based on tests so far)

**Comment by T-Rizzle12** [comment] 2024-08-30 16:10
I might be able to resolve the issues of what the bot will collide with by changing how the avoid trace checks works internally in the pathfinder. I will start working on tests and will inform you if I'm successful or not.

**Comment by T-Rizzle12** [comment] 2024-10-31 14:22
Did some more work on this, I might be able to fix this by checking the bot's collision group and add it to the avoid trace line logic. 
Here is a small snippet from the current TBotPathFollower::Avoid:
```lua
	local body = bot:GetTBotBody()
	local size = body:GetHullWidth() / 4
	local offset = size + 2
	local range = Either( bot:KeyDown( IN_SPEED ), 50, 30 )
	range = range * bot:GetModelScale()
	local door = nil
	
	local hullMin = Vector( -size, -size, bot:GetStepSize() + 0.1 )
	local hullMax = Vector( size, size, body:GetCrouchHullHeight() )
	--local nextStepHullMin = Vector( -size, -size, 2.0 * self:GetStepSize() + 0.1 )
	
	local leftFrom = bot:GetPos() + offset * left
	local leftTo = leftFrom + range * forward
	local isLeftClear = true
	local leftAvoid = 0.0
	
	local result = {}
	util.TraceHull( { start = leftFrom, endpos = leftTo, maxs = hullMax, mins = hullMin, filter = bot, mask = MASK_PLAYERSOLID, output = result } )
	if result.Fraction < 1.0 or result.StartSolid then
```
I could change the TraceHull call to use the current bot's collision group:
```lua
-- Grab the bot's current collision group
local botCollision = bot:GetCollisionGroup()
-- Rest of code omitted for readability
local result = {}
util.TraceHull( { start = leftFrom, endpos = leftTo, maxs = hullMax, mins = hullMin, filter = bot, mask = MASK_PLAYERSOLID, collisiongroup = botCollision, output = result } )
```
This could resolve the issue entirely. I will see if this works and if it does, I will add it to #68.

**Comment by T-Rizzle12** [comment] 2024-11-08 17:22
Ok, so far, I went ahead and tested these changes in a test game mode of mine. It seems to work for the SetNoCollideWithTeammates is set to true and the bot's team is between 1-4. It should also work if the player's collision group changes. Since it now considers the collision group's masks as well. I need to check for any regression that may occurs as a result of this change. If there are no regressions, I will update the TBotPathFollower file to this new code.

**Closed** 2024-11-17 22:03 UTC
Labels: bug
